[package]
name = "actix_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.4"
aws-sdk-cloudwatchlogs = "1.38.0"
chrono = "0.4.38"
env_logger = "0.11.3"
log = "0.4.22"
tokio = { version = "1.38.1", features = ["full"] }
dotenvy = "0.15.7"